[build]
  publish = "public"

[[redirects]]
  from = "/sqlite-wasm-demo/*"
  to = "https://vkbansal.github.io/sqlite-wasm-demo/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/data.js"
  to = "https://d.vkbansal.xyz/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/react-contextmenu"
  to = "https://vkbansal.github.io/react-contextmenu/"
  status = 301
