[build]
  publish = "public"
  command = "npm install -g pnpm && pnpm install --store=node_modules/.pnpm-store --frozen-lockfile && pnpm run build"

[build.environment]
  NPM_FLAGS="--version"
  NODE_VERSION="16"

[functions]
  directory = "src/_netlify/functions"
  # external_node_modules = ["mongodb"]

[[redirects]]
  from = "/sqlite-wasm-demo/*"
  to = "https://vkbansal.github.io/sqlite-wasm-demo/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/data.js"
  to = "https://d.vkbansal.xyz/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://d.vkbansal.xyz/api/event"
  status = 200
  force = true

[[redirects]]
  from = "/react-contextmenu"
  to = "https://vkbansal.github.io/react-contextmenu/"
  status = 301
