[build]
  command = "npm build"
  publish = "public"
  ignore = "./bot-test.sh"

[build.environment]
  NODE_VERSION = "v16"
  NODE_ENV = "production"

[[redirects]]
  from = "/sqlite-wasm-demo/*"
  to = "https://vkbansal.github.io/sqlite-wasm-demo/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/react-contextmenu"
  to = "https://vkbansal.github.io/react-contextmenu/"
  status = 301
