name: Main Branch Check
on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.*'
      - pnpm-lock.yaml
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@main
      - name: Lint
        run: pnpm run lint
  typecheck:
    name: TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@main
      - name: Type Check
        run: pnpm run check
  spellcheck:
    name: SpellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@main
      - name: Spell Check
        run: pnpm run spell
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: vkbansal/pnpm-setup-action@main
      - name: Prettier
        run: pnpm run fmt:c
